# Generated by Django 6.0.6 on 2026-07-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('ELETRONICO', 'Eletrônico'), ('FERRAMENTA', 'Ferramenta'), ('CONSUMIVEL', 'Consumível'), ('EQUIPAMENTO', 'Equipamento')], max_length=15)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('MANUTENCAO', 'Manutenção')], default='DISPONIVEL', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
