# Generated by Django 6.0.6 on 2026-07-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaLimpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira')])),
                ('semana_referencia', models.DateField(help_text='Data da segunda-feira da semana')),
                ('feito', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('documento_tecnico', models.FileField(blank=True, null=True, upload_to='projetos/docs/')),
                ('status', models.CharField(choices=[('A_FAZER', 'A Fazer'), ('FAZENDO', 'Fazendo'), ('CONCLUIDO', 'Concluído')], default='A_FAZER', max_length=10)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=6)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-prioridade', 'prazo'],
            },
        ),
    ]
