# Generated by Django 6.0.6 on 2026-07-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropresenca',
            name='tipo',
        ),
    ]
