# Generated by Django 6.0.6 on 2026-07-08 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_registropresenca_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta')])),
                ('slot', models.CharField(choices=[('M1', '07:00 – 08:30'), ('M2', '08:50 – 10:20'), ('M3', '10:30 – 12:00'), ('T1', '13:00 – 14:30'), ('T2', '14:50 – 16:20'), ('T3', '16:30 – 18:00')], max_length=2)),
                ('membros', models.ManyToManyField(blank=True, related_name='horarios_escala', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_semana', 'slot'],
                'unique_together': {('dia_semana', 'slot')},
            },
        ),
    ]
